# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaedicao.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edicao_Foto_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 649)
        self.slider = QtWidgets.QSlider(Form)
        self.slider.setGeometry(QtCore.QRect(150, 570, 311, 21))
        self.slider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.slider.setMaximum(255)
        self.slider.setProperty("value", 129)
        self.slider.setSliderPosition(129)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.slider.setVisible(False)
        self.slider.setEnabled(False)

        self.publicar = QtWidgets.QPushButton(Form)
        self.publicar.setGeometry(QtCore.QRect(550, 10, 86, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.publicar.setFont(font)
        self.publicar.setObjectName("publicar")

        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(-10, 370, 661, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1140, 142))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.filtro7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtro7.sizePolicy().hasHeightForWidth())
        self.filtro7.setSizePolicy(sizePolicy)
        self.filtro7.setMinimumSize(QtCore.QSize(135, 30))
        self.filtro7.setObjectName("filtro7")
        self.gridLayout.addWidget(self.filtro7, 0, 7, 1, 1)
        self.imagemCinza = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagemCinza.sizePolicy().hasHeightForWidth())
        self.imagemCinza.setSizePolicy(sizePolicy)
        self.imagemCinza.setMinimumSize(QtCore.QSize(135, 85))
        self.imagemCinza.setText("")
        self.imagemCinza.setScaledContents(True)
        self.imagemCinza.setObjectName("imagemCinza")
        self.gridLayout.addWidget(self.imagemCinza, 1, 2, 1, 1)
        self.imgaemSegmentada = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imgaemSegmentada.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgaemSegmentada.sizePolicy().hasHeightForWidth())
        self.imgaemSegmentada.setSizePolicy(sizePolicy)
        self.imgaemSegmentada.setMinimumSize(QtCore.QSize(135, 85))
        self.imgaemSegmentada.setText("")
        self.imgaemSegmentada.setScaledContents(True)
        self.imgaemSegmentada.setObjectName("imgaemSegmentada")
        self.gridLayout.addWidget(self.imgaemSegmentada, 1, 3, 1, 1)
        self.normal = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normal.sizePolicy().hasHeightForWidth())
        self.normal.setSizePolicy(sizePolicy)
        self.normal.setMinimumSize(QtCore.QSize(135, 30))
        self.normal.setObjectName("normal")
        self.gridLayout.addWidget(self.normal, 0, 1, 1, 1)
        self.imagemBlur = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagemBlur.sizePolicy().hasHeightForWidth())
        self.imagemBlur.setSizePolicy(sizePolicy)
        self.imagemBlur.setMinimumSize(QtCore.QSize(135, 85))
        self.imagemBlur.setText("")
        self.imagemBlur.setScaledContents(True)
        self.imagemBlur.setObjectName("imagemBlur")
        self.gridLayout.addWidget(self.imagemBlur, 1, 4, 1, 1)
        self.filtro6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtro6.sizePolicy().hasHeightForWidth())
        self.filtro6.setSizePolicy(sizePolicy)
        self.filtro6.setMinimumSize(QtCore.QSize(135, 30))
        self.filtro6.setObjectName("filtro6")
        self.gridLayout.addWidget(self.filtro6, 0, 6, 1, 1)
        self.cinzar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cinzar.sizePolicy().hasHeightForWidth())
        self.cinzar.setSizePolicy(sizePolicy)
        self.cinzar.setMinimumSize(QtCore.QSize(135, 30))
        self.cinzar.setObjectName("cinzar")
        self.gridLayout.addWidget(self.cinzar, 0, 2, 1, 1)
        self.blur = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blur.sizePolicy().hasHeightForWidth())
        self.blur.setSizePolicy(sizePolicy)
        self.blur.setMinimumSize(QtCore.QSize(135, 30))
        self.blur.setObjectName("blur")
        self.gridLayout.addWidget(self.blur, 0, 4, 1, 1)

        self.contraste = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contraste.sizePolicy().hasHeightForWidth())
        self.contraste.setSizePolicy(sizePolicy)
        self.contraste.setMinimumSize(QtCore.QSize(135, 30))
        self.contraste.setObjectName("contraste")


        self.gridLayout.addWidget(self.contraste, 0, 5, 1, 1)
        self.imagemContraste = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagemContraste.sizePolicy().hasHeightForWidth())
        self.imagemContraste.setSizePolicy(sizePolicy)
        self.imagemContraste.setMinimumSize(QtCore.QSize(135, 85))
        self.imagemContraste.setText("")
        self.imagemContraste.setScaledContents(True)
        self.imagemContraste.setObjectName("imagemContraste")
        self.gridLayout.addWidget(self.imagemContraste, 1, 5, 1, 1)
        self.imagemNormal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagemNormal.sizePolicy().hasHeightForWidth())
        self.imagemNormal.setSizePolicy(sizePolicy)
        self.imagemNormal.setMinimumSize(QtCore.QSize(135, 85))
        self.imagemNormal.setText("")
        self.imagemNormal.setScaledContents(True)
        self.imagemNormal.setObjectName("imagemNormal")
        self.gridLayout.addWidget(self.imagemNormal, 1, 1, 1, 1)
        self.filtro6_imagem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtro6_imagem.sizePolicy().hasHeightForWidth())
        self.filtro6_imagem.setSizePolicy(sizePolicy)
        self.filtro6_imagem.setMinimumSize(QtCore.QSize(135, 85))
        self.filtro6_imagem.setText("")
        self.filtro6_imagem.setScaledContents(True)
        self.filtro6_imagem.setObjectName("filtro6_imagem")
        self.gridLayout.addWidget(self.filtro6_imagem, 1, 6, 1, 1)
        self.segmentar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segmentar.sizePolicy().hasHeightForWidth())
        self.segmentar.setSizePolicy(sizePolicy)
        self.segmentar.setMinimumSize(QtCore.QSize(135, 30))
        self.segmentar.setObjectName("segmentar")
        self.gridLayout.addWidget(self.segmentar, 0, 3, 1, 1)
        self.filtro7_imagem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtro7_imagem.sizePolicy().hasHeightForWidth())
        self.filtro7_imagem.setSizePolicy(sizePolicy)
        self.filtro7_imagem.setMinimumSize(QtCore.QSize(135, 85))
        self.filtro7_imagem.setText("")
        self.filtro7_imagem.setScaledContents(True)
        self.filtro7_imagem.setObjectName("filtro7_imagem")
        self.gridLayout.addWidget(self.filtro7_imagem, 1, 7, 1, 1)
        self.filtro8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtro8.sizePolicy().hasHeightForWidth())
        self.filtro8.setSizePolicy(sizePolicy)
        self.filtro8.setMinimumSize(QtCore.QSize(135, 30))
        self.filtro8.setObjectName("filtro8")
        self.gridLayout.addWidget(self.filtro8, 0, 8, 1, 1)
        self.filtro8_imagem = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtro8_imagem.sizePolicy().hasHeightForWidth())
        self.filtro8_imagem.setSizePolicy(sizePolicy)
        self.filtro8_imagem.setMinimumSize(QtCore.QSize(135, 85))
        self.filtro8_imagem.setText("")
        self.filtro8_imagem.setScaledContents(True)
        self.filtro8_imagem.setObjectName("filtro8_imagem")
        self.gridLayout.addWidget(self.filtro8_imagem, 1, 8, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(0, 50, 651, 321))
        self.image_label.setText("")
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.botaoFiltro = QtWidgets.QPushButton(Form)
        self.botaoFiltro.setGeometry(QtCore.QRect(50, 600, 91, 41))
        self.botaoFiltro.setMinimumSize(QtCore.QSize(91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.botaoFiltro.setFont(font)
        self.botaoFiltro.setMouseTracking(False)
        self.botaoFiltro.setObjectName("botaoFiltro")
        self.botaoEditar = QtWidgets.QPushButton(Form)
        self.botaoEditar.setGeometry(QtCore.QRect(480, 600, 91, 41))
        self.botaoEditar.setMinimumSize(QtCore.QSize(91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.botaoEditar.setFont(font)
        self.botaoEditar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botaoEditar.setObjectName("botaoEditar")
        
        
        self.tirarFoto = QtWidgets.QPushButton(Form)
        self.tirarFoto.setGeometry(QtCore.QRect(10, 10, 86, 37))
        self.tirarFoto.setMinimumSize(QtCore.QSize(86, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tirarFoto.setFont(font)
        self.tirarFoto.setObjectName("tirarFoto")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.publicar.setText(_translate("Form", "PUBLICAR"))
        self.filtro7.setText(_translate("Form", "Filtro7"))
        self.normal.setText(_translate("Form", "Normal"))
        self.filtro6.setText(_translate("Form", "Filtro6"))
        self.cinzar.setText(_translate("Form", "Cinza"))
        self.blur.setText(_translate("Form", "Blur"))
        self.contraste.setText(_translate("Form", "Contraste"))
        self.segmentar.setText(_translate("Form", "Segmentar"))
        self.filtro8.setText(_translate("Form", "Filtro 8"))
        self.botaoFiltro.setText(_translate("Form", "Filtro"))
        self.botaoEditar.setText(_translate("Form", "Editar"))
        self.tirarFoto.setText(_translate("Form", "VOLTAR"))

